Description("v_levels_rgb_in_black", "f:EDIT;e:EDIT|SPINNER|EXPANDABLE|BROWSE_COLOR|SHOW_DESCRIPTION|DONT_SERIALIZE;m:0 0 0;x:1 1 1;s:0.01 0.01 0.01;c:Postprocess Levels;d:In Black;" )
Description("v_levels_rgb_in_gamma", "f:EDIT;e:EDIT|SPINNER|EXPANDABLE|BROWSE_COLOR|SHOW_DESCRIPTION|DONT_SERIALIZE;m:0 0 0;s:0.01 0.01 0.01;c:Postprocess Levels;d:In Gamma;" )
Description("v_levels_rgb_in_white", "f:EDIT;e:EDIT|SPINNER|EXPANDABLE|BROWSE_COLOR|SHOW_DESCRIPTION|DONT_SERIALIZE;m:0 0 0;x:1 1 1;s:0.01 0.01 0.01;c:Postprocess Levels;d:In White;" )
Description("v_levels_rgb_out_black", "f:EDIT;e:EDIT|SPINNER|EXPANDABLE|BROWSE_COLOR|SHOW_DESCRIPTION|DONT_SERIALIZE;m:0 0 0;x:1 1 1;s:0.01 0.01 0.01;c:Postprocess Levels;d:Out Black;" )
Description("v_levels_rgb_out_white", "f:EDIT;e:EDIT|SPINNER|EXPANDABLE|BROWSE_COLOR|SHOW_DESCRIPTION|DONT_SERIALIZE;m:0 0 0;x:1 1 1;s:0.01 0.01 0.01;c:Postprocess Levels;d:Out White;" )
Description("f_levels", "f:EDIT;e:EDIT|SPINNER|SHOW_DESCRIPTION|DONT_SERIALIZE;m:0.0;x:1.0;s:0.05;c:Postprocess Levels;d:Power;" )

