Description("f_noise", 			"f:EDIT;e:EDIT|SLIDER|SHOW_DESCRIPTION|DONT_SERIALIZE;m:0.0;x:1.0;s:0.001;c:Postprocess Noise;d:Strength;" )
Description("f_noise_speed",	"f:EDIT;e:EDIT|SLIDER|SHOW_DESCRIPTION|DONT_SERIALIZE;m:0.0;x:10.0;s:0.1;c:Postprocess Noise;d:Animation speed;" )
Description("f_noise_size",		"f:EDIT;e:EDIT|SLIDER|SHOW_DESCRIPTION|DONT_SERIALIZE;m:1.0;x:32.0;s:1.0;c:Postprocess Noise;d:Size;" )
Description("f_noise_color",	"f:EDIT;e:EDIT|SLIDER|SHOW_DESCRIPTION|DONT_SERIALIZE;m:0.0;x:1.0;s:0.05;c:Postprocess Noise;d:Color weight;" )
