Description( "v_ambient", "f:EDIT;e:EDIT|SPINNER|EXPANDABLE|BROWSE_COLOR|SHOW_DESCRIPTION;m:0 0 0;x:1 1 1;s:0.05 0.05 0.05;c:Ambient;d:Color;" )
Description( "f_ambient_mip", "f:EDIT;e:EDIT|SPINNER|SHOW_DESCRIPTION;m:0;s:0.5;x:5;c:Ambient;d:Cubemap mipmap no;" )
Description( "f_amb_saturation", "f:EDIT;e:EDIT|SPINNER|SHOW_DESCRIPTION;m:0;s:0.05;c:Ambient;d:Ambient Saturation;")
Description("f_lighting_indirect_factor", "f:EDIT;e:EDIT|SLIDER|SHOW_DESCRIPTION;m:0;s:0.01;x:1;c:Ambient;d:Indirect lighting factor;" )
