Description("f_shadows_offset", "f:EDIT;e:EDIT|SPINNER|SHOW_DESCRIPTION;s:0.1;c:Shadows Sun common;d:Offset;")
Description("i_shadows_count", "f:EDIT;e:EDIT|SLIDER|SHOW_DESCRIPTION;m:0;x:4;s:1;c:Shadows Sun common;d:Shadow map count;")
Description("f_shadow_depth_treshold", "f:EDIT;e:EDIT|SPINNER|SHOW_DESCRIPTION;m:0;s:0.01;c:Shadows;d:Shadow sun blur depth treshold;")
Description("f_shadow_radius_mult", "f:EDIT;e:EDIT|SPINNER|SHOW_DESCRIPTION;m:0;s:0.01;c:Shadows;d:Shadow blur radius;")

Description("f_engine_shadows_slice_size", "f:EDIT;e:EDIT|SPINNER|SHOW_DESCRIPTION;m:0.0;s:0.5;c:Shadows Sun new;d:Base slice size;")
Description("f_engine_shadows_slice_mul", "f:EDIT;e:EDIT|SPINNER|SHOW_DESCRIPTION;m:1.1;s:0.1;c:Shadows Sun new;d:Slice size multiplier;")
