Description("f_lum_pm", "f:EDIT;e:EDIT|SPINNER|SHOW_DESCRIPTION|DONT_SERIALIZE;m:0;s:0.05;c:Postprocess Luminance PreMultiply;d:Power;" )
Description("v_lum_pm_factors", "f:EDIT;e:EDIT|SPINNER|EXPANDABLE|BROWSE_COLOR|SHOW_DESCRIPTION|DONT_SERIALIZE;m:0 0 0;s:0.05 0.05 0.05;c:Postprocess Luminance PreMultiply;d:Factors;" )
Description("v_lum_pm_weights", "f:EDIT;e:EDIT|SPINNER|EXPANDABLE|BROWSE_COLOR|SHOW_DESCRIPTION|DONT_SERIALIZE;m:0 0 0;x:1 1 1;s:0.01 0.01 0.01;c:Postprocess Luminance PreMultiply;d:Weights;" )
Description("f_lum_pm_weights_factor", "f:EDIT;e:EDIT|SPINNER|SHOW_DESCRIPTION|DONT_SERIALIZE;m:0;s:0.05;c:Postprocess Luminance PreMultiply;d:Weigths factor;" )
