Description("f_desaturate", "f:EDIT;e:EDIT|SPINNER|SHOW_DESCRIPTION|DONT_SERIALIZE;m:0.0;x:1.0;s:0.05;c:Postprocess - desaturation;d:Image desaturation value;" )
Description("v_desaturate_factor_lum", "f:EDIT;e:EDIT|SPINNER|EXPANDABLE|DONT_SERIALIZE;s:0.05 0.05 0.05;c:Postprocess - desaturation;d:Luminance factors;" )
Description("v_desaturate_factor_mask", "f:EDIT;e:EDIT|SPINNER|EXPANDABLE|DONT_SERIALIZE;s:0.05 0.05 0.05;c:Postprocess - desaturation;d:Mask factors;" )
Description("v_desaturate_tint", "f:EDIT;e:EDIT|SPINNER|EXPANDABLE|DONT_SERIALIZE;s:0.05 0.05 0.05;c:Postprocess - desaturation;d:Desautrated image tint;" )
Description("v_desaturate_tint_masked", "f:EDIT;e:EDIT|SPINNER|EXPANDABLE|DONT_SERIALIZE;s:0.05 0.05 0.05;c:Postprocess - desaturation;d:Saturated image tint;" )

Description("f_desaturate_lum_mask", "f:EDIT;e:EDIT|SLIDER|SHOW_DESCRIPTION|DONT_SERIALIZE;m:0.0;x:1.0;s:0.01;c:Postprocess - desaturation by lum;d:Desaturation strength;" )
Description("f_desaturate_lum_mask_min", "f:EDIT;e:EDIT|SLIDER|SHOW_DESCRIPTION|DONT_SERIALIZE;m:0.0;x:1.0;s:0.01;c:Postprocess - desaturation by lum;d:Desaturation mask min;" )
Description("f_desaturate_lum_mask_max", "f:EDIT;e:EDIT|SLIDER|SHOW_DESCRIPTION|DONT_SERIALIZE;m:0.0;x:1.0;s:0.01;c:Postprocess - desaturation by lum;d:Desaturation mask max;" )
