Description("f_prv_copy", "f:EDIT;e:EDIT|SLIDER|SHOW_DESCRIPTION|DONT_SERIALIZE;m:0.0;s:1.0;x:1.0;c:Previous frame;d:Copy;")
Description("f_prv_lrp", "f:EDIT;e:EDIT|SLIDER|SHOW_DESCRIPTION|DONT_SERIALIZE;m:0.0;s:0.05;x:1.0;c:Previous frame;d:Blend;")
Description("f_prv_mul", "f:EDIT;e:EDIT|SLIDER|SHOW_DESCRIPTION|DONT_SERIALIZE;m:0.0;s:0.05;x:1.0;c:Previous frame;d:Multiply;")
Description("f_prv_add", "f:EDIT;e:EDIT|SLIDER|SHOW_DESCRIPTION|DONT_SERIALIZE;m:0.0;s:0.05;x:1.0;c:Previous frame;d:Add;")
