Description( "f_exposure_factor", "f:EDIT;e:EDIT|SPINNER|SHOW_DESCRIPTION|DONT_SERIALIZE;m:0;s:0.05;c:Exposure;d:Exposure factor;" )


Description( "f_auto_exposure_adaptation_rate", "f:EDIT;e:EDIT|SPINNER|SHOW_DESCRIPTION|DONT_SERIALIZE;s:0.01;c:Exposure DX11;d:f_Auto Exposure Adapatation Rate;" )
Description( "f_auto_exposure_key_value", "f:EDIT;e:EDIT|SPINNER|SHOW_DESCRIPTION|DONT_SERIALIZE;m:0.0;s:0.01;c:Exposure DX11;d:Auto Exposure Key Value;" )
Description( "f_auto_exposure_white", "f:EDIT;e:EDIT|SPINNER|SHOW_DESCRIPTION|DONT_SERIALIZE;m:0.0;s:0.01;c:Exposure DX11;d:Auto Exposure White Intensity;" )

Description( "f_auto_exposure_max", "f:EDIT;e:EDIT|SPINNER|SHOW_DESCRIPTION|DONT_SERIALIZE;s:0.1;c:Exposure;d:Auto Exposure Max;" )
Description( "f_auto_exposure_min", "f:EDIT;e:EDIT|SPINNER|SHOW_DESCRIPTION|DONT_SERIALIZE;s:0.1;c:Exposure;d:Auto Exposure Min;" )
