Description("f_blur_camera_motion_factor", "f:EDIT;e:EDIT|SPINNER|DONT_SERIALIZE;m:0;s:0.1;c:Camera Motion Blur;d:Strength;" )
Description("f_blur_camera_motion_near", "f:EDIT;e:EDIT|SPINNER|DONT_SERIALIZE;m:0;s:1.0;c:Camera Motion Blur;d:Mask Near;" )
Description("f_blur_camera_motion_far", "f:EDIT;e:EDIT|SPINNER|DONT_SERIALIZE;m:0;s:1.0;c:Camera Motion Blur;d:Mask Far;" )
Description("f_blur_camera_motion_max", "f:EDIT;e:EDIT|SPINNER|DONT_SERIALIZE;m:0;s:0.1;x:10;c:Camera Motion Blur;d:Maximum value;" )
