!include("varlist_lighting.scr")

VarVec3( "v_pp_shading_sun_color", [1.0, 1.0, 1.0] )
VarVec3( "v_pp_shading_sun_color_clouds_fade", [1.0, 1.0, 1.0] )
VarVec3( "v_pp_shading_sun_color_only", [1.0, 1.0, 1.0] )
VarVec3( "v_pp_shading_sun_color_clouds_off", [1.0, 1.0, 1.0] )
VarVec3( "v_pp_shading_sun_color_clouds_fade_only", [1.0, 1.0, 1.0] )
VarVec3( "v_pp_derived_sun_color", [1.0, 1.0, 1.0] ) //obsolete - remove
VarFloat("f_pp_lightning_on", 0.0)

