!include("varlist_blur_radial.scr")

VarFloat("f_pp_blur_radial_center_x", 0.5)
VarFloat("f_pp_blur_radial_center_y", 0.5)
VarFloat("f_pp_blur_radial_mask_bias", 0.0)
VarFloat("f_pp_blur_radial_mask_scale", 1.0)
VarFloat("f_pp_blur_radial_mask_opacity", 0.0)
VarFloat("f_pp_blur_radial_power", 0.0)
VarFloat("f_pp_blur_radial_range", 0.0)
VarInt("i_pp_blur_radial_samples", 10)

VarFloat("f_pp_blur_radial_on", 0.0)
