!include("varlist_underwater.scr")

VarFloat("f_pp_underwater_surface_level", 0.0)
VarVec3("v_pp_underwater_extinction_factors", [ 0.0, 0.0, 0.0 ])
VarVec3("v_pp_underwater_inscattering_factors", [ 0.0, 0.0, 0.0 ])
VarVec3("v_pp_underwater_deep_clr", [0.0, 0.0, 0.0])
VarVec4("v_pp_underwater_nrm_waves_0", [0.031, 0.011,  -0.01,  0.01])
VarVec4("v_pp_underwater_nrm_waves_1", [0.021, 0.011,  0.01,  -0.01])
